# Nintendo Switch platform configuration -- no Linux imports.
if (current_toolchain == default_toolchain &&
    build_with_separate_cobalt_toolchain) {
  platform_tests_path = ""
  cobalt_font_package = "standard"
} else {
  sb_evergreen_compatible_use_libunwind = use_evergreen
  sabi_path = "//starboard/sabi/arm64/sabi-v18.json"
}
sb_enable_benchmark = true
